### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by Psiiirus** [manelpb/videojs-qualityselector#6]
Hiya,
can you please tag stable versions?

Cheers,
Toni

**Comment by manelpb** [comment]
Sure! There's any issue with the current version?

**Comment by MM-Psiiirus** [comment]
well npm isn't picking up 0.0.3 :) thats the main reason for me ;)

But unf. its also not working with webpack and es6 import if i do an npm install ...not sure why but it worked after copy and import the plugin.js into my source folder.
