### ISSUE TITLE
Selected Format Not Indicated

### ISSUE THREAD

**Issue by GlitterCakes** [manelpb/videojs-qualityselector#8]
The currently selected format is nowhere indicated as selected. It probably should because on page load you have no idea what you're looking at by default. Why not replace the word "Quality" with the currently chosen format name? This is how YouTube and other popular video players do it.

**Comment by justingivens** [comment]
@GlitterCakes you could do this:
`player.qualityselector({
		...other code...
		onFormatSelected: function (format) {
			document.getElementsByClassName('vjs-brand-quality-link').item(0).innerHTML = format.name;
		}
	});`

This will update Quality to the format.name that you defined.

**Comment by GlitterCakes** [comment]
Thank you

**Comment by justingivens** [comment]
I agree, I'm working on a pull request to do this by in the plugin itself and also on video source change to keep the current time.

**Comment by manelpb** [comment]
hey guys, i just released a new version 0.0.4 with this fix and other small improvements. I'm closing this thread as this issue is now fixed.
